language: python
python:
 - "3.6"
 - "3.7"
 - "3.8"
 - "3.9"
 - "3.10"
 - "3.11"
addons:
  apt:
    sources:
      - sourceline: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main
        key_url: https://packages.microsoft.com/keys/microsoft.asc
      - sourceline: deb http://download.mono-project.com/repo/ubuntu stable-xenial/snapshots/5.20 main
        key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF
    packages:
      - mono-devel
      - ca-certificates-mono
      - dotnet-hostfxr-5.0
      - dotnet-runtime-5.0
      - dotnet-sdk-5.0
install:
 - pip install -r requirements.txt
 - pip install codecov
 - pip install pytest-cov
 - python setup.py develop
 - pip install .
script: 
 - pytest --cov-report=xml --cov=pandasnet tests/

after_success:
 - codecov -t $CODECOV_TOKEN

deploy:
  - provider: pypi
    user: __token__
    password: $FDIEULLE_PYPI_TOKEN
    distributions: "sdist bdist_wheel"
    skip_existing: true
    on:
      tags: true
      python: "3.8"
  - provider: release
    api_key: $GITHUB_TOKEN
    on:
      tags: true
      python: "3.8"
  
