on:
  push:
    tags:
      - '*'

name: Release

jobs:
  autorelease:
    name: Create Release
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install wheel
          pip install -r requirements.txt
      - name: Add version to environment vars
        run: |
          PROJECT_VERSION=$(git describe HEAD --tags --abbrev=0)
          echo $PROJECT_VERSION
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - name: Run tests
        run: pytest tests/
      - name: Release Notes
        run: git log $(git describe HEAD~ --tags --abbrev=0)..HEAD --pretty='format:* %h %s%n  * %an <%ae>' --no-merges >> ".github/release_template.md"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ".github/release_template.md"
          files: |
            dist/pandasnet-${{env.PROJECT_VERSION}}-py3-none-any.whl
            dist/pandasnet-${{env.PROJECT_VERSION}}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
